import Titulo from '@/components/Titulo'

export default function Layout(Layout.props) {
  return (
    <div className={`
      flex flex-col w-2/3 
      bg-white text-gray-800
    `}>
      <div>
        <Titulo></Titulo>
      </div>
    </div>
  )
}

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { decodeAction } from 'next/dist/server/app-render/entry-base'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
